version: '3.9'
services:
  minio:
    hostname: minio1          # rename on different nodes
    image: quay.io/minio/minio:RELEASE.2023-05-04T21-44-30Z
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server --console-address=":9001" http://minio{1...2}/data
    extra_hosts:
      - minio1:192.168.14.252 # change ip on different nodes
      - minio2:192.168.14.72  # change ip on different nodes
    ports:
      - ${MINIO_PORT}:9000
      - ${MINIO_CONSOLE_PORT}:9001
    volumes:
      - ${MINIO_DATA_PATH}:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3